nam: Verification de conformité PEP8
on:
	push:
		branch:
			- main
jobs:
	pep8_check:
		name:Vérification PEP8
		runs-on: ubuntu-latest

		steps:
		- name: Checkout du code source
		  run: sudo apt && sudo apt install -y python3 

		- name:Vérification de conformité PEP8
		  run:python3 -m pip install flake8
		- name: Analyse du code avec flake8
			run: flake8
